apiVersion: v1
kind: ServiceAccount
metadata:
  name: python-client-sa
  namespace: spark-operator
---
# needed for kubernetes 1.24 onwards, token is not created automatically
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: python-client-sa-token
  namespace: spark-operator
  annotations:
    kubernetes.io/service-account.name: "python-client-sa"